#! /bin/sh

set -e

case "$1" in

	configure)
		chown -R irc:irc /etc/inspircd
		chmod 770 /etc/inspircd
        mkdir -p /var/run/inspircd
        chown irc:irc /var/run/inspircd
        mkdir -p /var/log/ircd
        chown irc:irc /var/log/ircd
        chmod 750 /var/log/ircd
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		echo "ERROR: Postinst called with unknown argument!"
		exit 0
	;;

esac

#DEBHELPER#

exit 0
